"""Native Gemini schema definitions for memory engines."""

from .fact_extraction import FACT_EXTRACTION_SYSTEM_INSTRUCTION, FACT_EXTRACTION_SCHEMA
from .topic_segmentation import TOPIC_SEGMENTATION_SYSTEM_INSTRUCTION, TOPIC_SEGMENTATION_SCHEMA

__all__ = [
    "FACT_EXTRACTION_SYSTEM_INSTRUCTION",
    "FACT_EXTRACTION_SCHEMA",
    "TOPIC_SEGMENTATION_SYSTEM_INSTRUCTION",
    "TOPIC_SEGMENTATION_SCHEMA",
]
